"""Method-neutral records used by GrowRAG experiments."""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum


class Action(StrEnum):
    """Mutually exclusive actions evaluated for one target query."""

    DIRECT = "direct"
    REUSE = "reuse"
    FRESH = "fresh"


@dataclass(frozen=True, slots=True)
class EnvironmentFingerprint:
    """The environment in which a transformation was validated."""

    corpus_id: str
    corpus_version: str
    retriever_id: str
    retriever_version: str
    rewriter_id: str
    rewriter_version: str
    index_id: str = "unspecified"
    index_version: str = "unspecified"
    analyzer_id: str = "unspecified"
    analyzer_version: str = "unspecified"

    def retrieval_compatible_with(self, other: EnvironmentFingerprint) -> bool:
        """Return whether two records share the same retrieval environment.

        Rewriter identity is provenance rather than a hard read-time constraint:
        a prepared target-query variant may be generated by a different adapter.
        """

        left = self._retrieval_identity()
        right = other._retrieval_identity()
        if any(_is_unspecified(value) for value in (*left, *right)):
            return False
        return left == right

    def _retrieval_identity(self) -> tuple[str, ...]:
        return (
            self.corpus_id,
            self.corpus_version,
            self.retriever_id,
            self.retriever_version,
            self.index_id,
            self.index_version,
            self.analyzer_id,
            self.analyzer_version,
        )


@dataclass(frozen=True, slots=True)
class QueryTransformation:
    """A concrete, provenance-carrying query transformation.

    This record deliberately stores no global trust score. Historical reliability
    and current-query applicability are separate experimental quantities.
    """

    experience_id: str
    source_query_id: str
    source_query: str
    transformed_query: str
    atomic_units: tuple[str, ...]
    environment: EnvironmentFingerprint
    provenance: str
    transformation_type: str = "unspecified"
    application_note: str = ""
    applicability_signature: tuple[str, ...] = ()
    source_dataset_id: str = "unspecified"
    source_split: str = "unspecified"
    source_group_id: str = "unspecified"


@dataclass(frozen=True, slots=True)
class PreparedReuseCandidate:
    """A target-specific query variant produced from one historical experience.

    Candidate generation is deliberately outside the trust gate. This keeps the
    question "how was the variant produced?" separate from "should it be used?".
    """

    target_query_id: str
    target_query: str
    experience_id: str
    transformed_query: str
    generated_by: str
    estimated_cost: float = 0.0
    application_version: str = "unspecified"
    retrieval_query_count: int = 1
    requested_top_k: int = 0
    context_token_budget: int = 0

    def __post_init__(self) -> None:
        if not self.target_query.strip():
            raise ValueError("target_query must not be empty")
        if not self.transformed_query.strip():
            raise ValueError("transformed_query must not be empty")
        if self.estimated_cost < 0:
            raise ValueError("estimated_cost must be non-negative")
        if self.retrieval_query_count < 1:
            raise ValueError("retrieval_query_count must be at least 1")
        if self.requested_top_k < 0 or self.context_token_budget < 0:
            raise ValueError("retrieval budgets must be non-negative")


def _is_unspecified(value: str) -> bool:
    return not value.strip() or value.strip().casefold() in {"unset", "unspecified", "unknown"}
