"""Method-neutral records used by GrowRAG experiments."""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

SUPPORTED_GAP_CATEGORIES = frozenset(
    {"bridge_entity", "attribute", "relation", "evidence_span", "other"}
)


class Action(StrEnum):
    """Mutually exclusive actions evaluated for one target query."""

    DIRECT = "direct"
    REUSE = "reuse"
    FRESH = "fresh"


@dataclass(frozen=True, slots=True)
class EnvironmentFingerprint:
    """The environment in which a transformation was validated."""

    corpus_id: str
    corpus_version: str
    retriever_id: str
    retriever_version: str
    rewriter_id: str
    rewriter_version: str
    index_id: str = "unspecified"
    index_version: str = "unspecified"
    analyzer_id: str = "unspecified"
    analyzer_version: str = "unspecified"

    def retrieval_compatible_with(self, other: EnvironmentFingerprint) -> bool:
        """Return whether two records share the same retrieval environment.

        Rewriter identity is provenance rather than a hard read-time constraint:
        a prepared target-query variant may be generated by a different adapter.
        """

        left = self._retrieval_identity()
        right = other._retrieval_identity()
        if any(_is_unspecified(value) for value in (*left, *right)):
            return False
        return left == right

    def _retrieval_identity(self) -> tuple[str, ...]:
        return (
            self.corpus_id,
            self.corpus_version,
            self.retriever_id,
            self.retriever_version,
            self.index_id,
            self.index_version,
            self.analyzer_id,
            self.analyzer_version,
        )


@dataclass(frozen=True, slots=True)
class QueryTransformation:
    """A concrete, provenance-carrying query transformation.

    This record deliberately stores no global trust score. Historical reliability
    and current-query applicability are separate experimental quantities.

    ``diagnosed_failure`` and ``gap_categories`` describe what was missing on
    the source query. ``atomic_units`` remain the concrete repair operations.
    ``applicability_signature`` lists positive reuse conditions, while
    ``contraindication_signature`` lists conditions under which reuse should be
    avoided. These are source-card metadata, not post-retrieval control flow.
    """

    experience_id: str
    source_query_id: str
    source_query: str
    transformed_query: str
    atomic_units: tuple[str, ...]
    environment: EnvironmentFingerprint
    provenance: str
    transformation_type: str = "unspecified"
    application_note: str = ""
    applicability_signature: tuple[str, ...] = ()
    source_dataset_id: str = "unspecified"
    source_split: str = "unspecified"
    source_group_id: str = "unspecified"
    diagnosed_failure: str = ""
    gap_categories: tuple[str, ...] = ()
    contraindication_signature: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        if not isinstance(self.diagnosed_failure, str):
            raise ValueError("diagnosed_failure must be a string")
        object.__setattr__(self, "diagnosed_failure", self.diagnosed_failure.strip())
        object.__setattr__(
            self,
            "gap_categories",
            _normalize_gap_categories(self.gap_categories),
        )
        object.__setattr__(
            self,
            "applicability_signature",
            _normalize_signature_tuple(
                self.applicability_signature,
                field_name="applicability_signature",
            ),
        )
        object.__setattr__(
            self,
            "contraindication_signature",
            _normalize_signature_tuple(
                self.contraindication_signature,
                field_name="contraindication_signature",
            ),
        )


@dataclass(frozen=True, slots=True)
class PreparedReuseCandidate:
    """A target-specific query variant produced from one historical experience.

    Candidate generation is deliberately outside the trust gate. This keeps the
    question "how was the variant produced?" separate from "should it be used?".
    """

    target_query_id: str
    target_query: str
    experience_id: str
    transformed_query: str
    generated_by: str
    estimated_cost: float = 0.0
    application_version: str = "unspecified"
    retrieval_query_count: int = 1
    requested_top_k: int = 0
    context_token_budget: int = 0

    def __post_init__(self) -> None:
        if not self.target_query.strip():
            raise ValueError("target_query must not be empty")
        if not self.transformed_query.strip():
            raise ValueError("transformed_query must not be empty")
        if self.estimated_cost < 0:
            raise ValueError("estimated_cost must be non-negative")
        if self.retrieval_query_count < 1:
            raise ValueError("retrieval_query_count must be at least 1")
        if self.requested_top_k < 0 or self.context_token_budget < 0:
            raise ValueError("retrieval budgets must be non-negative")


def _is_unspecified(value: str) -> bool:
    return not value.strip() or value.strip().casefold() in {"unset", "unspecified", "unknown"}


def _normalize_gap_categories(values: tuple[str, ...]) -> tuple[str, ...]:
    if not isinstance(values, tuple):
        raise ValueError("gap_categories must be a tuple of strings")
    normalized: list[str] = []
    for index, value in enumerate(values):
        if not isinstance(value, str):
            raise ValueError(f"gap_categories[{index}] must be a string")
        category = "_".join(value.strip().casefold().replace("-", " ").split())
        if not category:
            raise ValueError(f"gap_categories[{index}] must not be blank")
        if category not in SUPPORTED_GAP_CATEGORIES:
            supported = ", ".join(sorted(SUPPORTED_GAP_CATEGORIES))
            raise ValueError(f"unsupported gap category {value!r}; expected one of: {supported}")
        if category in normalized:
            raise ValueError(f"duplicate normalized gap category: {category}")
        normalized.append(category)
    return tuple(normalized)


def _normalize_signature_tuple(
    values: tuple[str, ...],
    *,
    field_name: str,
) -> tuple[str, ...]:
    if not isinstance(values, tuple):
        raise ValueError(f"{field_name} must be a tuple of strings")
    normalized: list[str] = []
    for index, value in enumerate(values):
        if not isinstance(value, str):
            raise ValueError(f"{field_name}[{index}] must be a string")
        signature = " ".join(value.strip().casefold().split())
        if not signature:
            raise ValueError(f"{field_name}[{index}] must not be blank")
        if signature in normalized:
            raise ValueError(f"duplicate normalized {field_name}: {signature}")
        normalized.append(signature)
    return tuple(normalized)
